#include <msp430.h>
#include <string.h>
#include <stdio.h>
#include "uart.h"


int handle_adc; 
//added the interrupt if statements for each memory location 
void adc_int(void) __interrupt[ADC12_VECTOR]{//this is an interrupt function the _interrupt tells its a function interrupt 
  handle_adc = 1;
  //P7OUT=BIT1;
  ADC12IFG=0;
  ADC12CTL0|=ADC12SC;//need another comment 
  /*#define ARR_LENGTH 8
  volatile unsigned int *arr = &ADC12MEM0;// creates a pointer, looks at the memory of mem0
  int i; 
  P7OUT=BIT1;
  ADC12CTL0|=ADC12SC;
  for (i=0; i<ARR_LENGTH; ++i)
  {
    if (arr[i] > 2050)
    {
      //P7OUT |= 1<<i;
    }
    else 
    {
      //P7OUT &= ~(1<<i);
    }
  }*/
}

void adcsetup(void){
//setting up A0-A7 for ADC 

  P6SEL = 0XFF; // DISABLES THE DITIGAL FUNCTION OF PORT 6. MAKES THEM ALL ANALOG CAPABLE
  //BITS SET TO DEFINE ADC12 FOR SINGLE CHANNEL MODE
  ADC12CTL0 = SHT0_3 | ADC12ON | ADC12SC | MSC; // SAMPELING FOR 32 CLOCK CYCLES | ADC12 IS ON | START OF CONVERSION |CONVERT AUTOMATICALLY MULTISAMPMODE
  ADC12CTL1 = CSTARTADD_0 | SHS_1 | SHP | ADC12DIV_0 | ADC12SSEL_0 | CONSEQ_1; // 
  //conversion start address AT MEM0,SAMPLE AND SOURCE SELLECT TIMER_A.OUT1 BIT,SET FOR PULSE MODE,CLK DIVIDE BY 1,USED ADC12 INTERNAL CLOCK,REPEATED MULTICHANNEL MODE

  // SET ALL THE CORESPONDING MEMEORY REGISTERS WITH CORESPONDING INPUT CHANNEL
  ADC12MCTL0 = SREF_0 | INCH_0; //USED SOURCE VOLTAGE TO COMPARE RAILS | INPUT CHANNEL IS A0
  ADC12MCTL1 = SREF_0 | INCH_1; //USED SOURCE VOLTAGE TO COMPARE RAILS | INPUT CHANNEL IS A1
  ADC12MCTL2 = SREF_0 | INCH_2; //USED SOURCE VOLTAGE TO COMPARE RAILS | INPUT CHANNEL IS A2
  ADC12MCTL3 = SREF_0 | INCH_3; //USED SOURCE VOLTAGE TO COMPARE RAILS | INPUT CHANNEL IS A3
  ADC12MCTL4 = SREF_0 | INCH_4; //USED SOURCE VOLTAGE TO COMPARE RAILS | INPUT CHANNEL IS A4
  ADC12MCTL5 = SREF_0 | INCH_5; //USED SOURCE VOLTAGE TO COMPARE RAILS | INPUT CHANNEL IS A5
  ADC12MCTL6 = SREF_0 | INCH_6; //USED SOURCE VOLTAGE TO COMPARE RAILS | INPUT CHANNEL IS A6
  ADC12MCTL7 = SREF_0 | INCH_7 | EOS; //USED SOURCE VOLTAGE TO COMPARE RAILS | INPUT CHANNEL IS A7| END OF SEQUENCE

  ADC12IFG = 0; // SET ALL FLAGS TO 0

  ADC12IE = BIT7; // ENABLE THE INTERUPTS FOR IE7

  //ADC12IE = 0;


//ENABLE CONVERSION BIT
  ADC12CTL0 |= ENC; // SET ENABLE BIT TO START CONVERSION 



//I COMMENTED THIS OUT, IT WAS FOR ORINGAL CODE TO GET ONE SAMPLE OF THE ADC TO SHOW UP IN THE DEBUGGER 
//ADC12CTL0 |= ADC12SC; // START SAMPLE AND CONVERSTION 

//while ( !(ADC12IFG & BIT0)); // THIS LOOPS WHILE THE FLAG IS NOT SET, ONCE IT SETS AND CONVERSION IS COMPLEATE IS MOVES ON AND CREATES THE RESULT


//__no_operation();
// P7DIR = 0XFF;
}

